---
# Source: demo/charts/demo-cronjob/templates/deployment.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name:  dev-cronjob
  namespace: dev
  labels:
    app: cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dev-cronjob-container
            image: demo/cronjob:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-configmap
                  key: application_port
          restartPolicy: OnFailure
