apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: demo
  labels:
    app: webapp
  annotations:
    note: "This is a webapp"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: demo/webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000