{{- $name := printf "%s-%s" .Release.Name .Values.webapp.name -}}
{{- $containername := printf "%s-%s-container" .Release.Name .Values.webapp.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webapp.name }}
  annotations:
    note: "This is a webapp"
spec:
  replicas: {{ .Values.webapp.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
      - name: {{ $containername }}
        image: {{ .Values.webapp.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.webapp.containerPort }}
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
