{{- $name := printf "%s-%s" .Release.Name .Values.webapp.name -}}
{{- $containername := printf "%s-%s-container" .Release.Name .Values.webapp.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.webapp.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.webapp.port }}
      targetPort: {{ .Values.webapp.containerPort }}
      nodePort: {{ .Values.webapp.nodePort }}